// "use client";

import './globals.css'

export const metadata = {
  title: 'ConsultMe',  // WisdomHub | Guidely | ExpertEase | AdviceArena | MentorMatch
                       // Conexa | AskPro/Me | ExperTip | Wisely | InSight
                       // ConsultMe/Hub | MentorMe | 


  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content={metadata.description} />
        <title>{metadata.title}</title>
      </head>
      <body className="chakra-ui-dark">
        {children}
      </body>
    </html>
  )
}
